development: &development
  adapter: postgresql
  database: recipes_development
  username: moiseszaragoza
  host:     localhost
  port:     5432
  schema_search_path: public
  min_messages: warning

test:
  <<: *development
  database: recipes_test

cucumber:
  database: recipes_cucumber
